[package]
name = "arcadia"
version = "1.0.0"
authors = ["Arcadia Team"]

[addresses]
arcadia = "57ef10b60a1c9027598887e41b8590c16b9ab3c660e883e363706a4294a49066"
std = "0x1"
aptos_framework = "0x1"
aptos_token_objects = "0x4"

[dev-addresses]
arcadia = "57ef10b60a1c9027598887e41b8590c16b9ab3c660e883e363706a4294a49066"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "mainnet" }
AptosTokenObjects = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-token-objects/", rev = "mainnet" }

[dev-dependencies]
