[package]
name = "Hero"
version = "0.0.1"

[addresses]
hero = "0x1234"
minter = "0x5678"
initial_creator_addr = "0x9abc"
launchpad_addr = "0xdef0"

[dev-addresses]
hero = "0x12345678"
minter = "0x87654321"
initial_creator_addr = "0x11111111"
launchpad_addr = "0x22222222"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }
AptosTokenObjects = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-token-objects" }

[dev-dependencies]
