[package]
name = "Hero"
version = "0.0.1"

[addresses]
hero = "0x3f2bb5c649e701c17e9a092e913c8884219ab8e6ed67c814c026f743f68cd2a3"

[dev-addresses]
hero = "0x12345678"
minter = "0x87654321"
initial_creator_addr = "0x11111111"
launchpad_addr = "0x22222222"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }
AptosTokenObjects = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-token-objects" }

[dev-dependencies]
